# Generated by Django 4.1.7 on 2023-03-11 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csvreader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('normal', 'Normal Game'), ('grandJackpot', 'Grand Jackpot'), ('correct_score', 'Correct Score'), ('megaJackpot', 'Mega jakpot'), ('ft/cs', 'FT/CS'), ('over/under1.5', 'Over/Under 1.5'), ('ht/cs', 'HT/CS'), ('supermultibet', 'Super Multibet')], max_length=15)),
                ('Teams', models.TextField(default='manU', max_length=300)),
                ('time', models.TimeField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunningTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
